Repository ingecarlos/RENAPSys, pull requests merged in 2020-01, with the labels that each got.

#125 Update index.php
  microservicios/servicio_divorcio/getDivorcios/index.php
Labels: microservicio

#126 cliente externo
  Jenkinsfile
  Renapsysexterno/Dockerfile
Labels: cliente_externo

#128 Update index.php
  Renapsysexterno/.env
  Renapsysexterno/.gitignore
  microservicios/servicio_nacimiento/setNacimiento/index.php
Labels: cliente_externo, configuracion, microservicio

#130 Update .env
  Renapsysexterno/.env
Labels: cliente_externo

#131 Update Jenkinsfile
  Jenkinsfile
Labels: cliente_externo

#132 Update Jenkinsfile
  Jenkinsfile
Labels: cliente_externo

#133 Update Dockerfile
  Renapsysexterno/Dockerfile
Labels: cliente_externo

#135 Update Jenkinsfile
  Jenkinsfile
Labels: cliente_externo

#139 Update Jenkinsfile
  Jenkinsfile
Labels: cliente_externo

#140 externo
  RENAPSysE/.env
  RENAPSysE/.gitignore
Labels: cliente_externo

#141 Update Dockerfile
  RENAPSysE/Dockerfile
Labels: cliente_externo

#142 Update .env
  RENAPSysE/.env
Labels: cliente_externo

#143 Update Dockerfile
  RENAPSysE/Dockerfile
Labels: cliente_externo

#144 Update Dockerfile
  RENAPSysE/Dockerfile
Labels: cliente_externo

#145 externo
  Jenkinsfile
  RENAPSysE/Dockerfile
Labels: cliente_externo

#146 Update Dockerfile
  RENAPSysE/Dockerfile
Labels: cliente_externo

#147 Update Dockerfile
  RENAPSysE/Dockerfile
Labels: cliente_externo

#148 cliente interno
  RENAPSys/app/Http/Controllers/DefuncionController.php
  RENAPSys/app/Http/Controllers/DivorcioController.php
  RENAPSys/app/Http/Controllers/DpiController.php
  RENAPSys/app/Http/Controllers/LicenciaController.php
  RENAPSys/app/Http/Controllers/MatrimonioController.php
  RENAPSys/app/Http/Controllers/NacimientoController.php
  RENAPSys/resources/views/defuncion.blade.php
  RENAPSys/resources/views/divorcio.blade.php
  RENAPSys/resources/views/dpi.blade.php
  RENAPSys/resources/views/licencia.blade.php
  RENAPSys/resources/views/licenciaActualizar.blade.php
  RENAPSys/resources/views/matrimonio.blade.php
  RENAPSys/resources/views/nacimiento.blade.php
Labels: cliente_externo, cliente_interno
